// app/layout.tsx
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Artisan Linkup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased flex flex-col min-h-screen`}
      >
        {/* Navbar consistent across all pages */}
        <Navbar />

        {/* Main content for page-specific components */}
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
